env:
  browser: true
  commonjs: true
  es6: true
extends: 
  - 'eslint:recommended'
  - 'plugin:node/recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  semi:
    - error
    - always
